"use client";

import { useEffect, useState } from "react";
import { Eye, ShieldOff } from "lucide-react";
import { toast } from "sonner";
import { AdminShell } from "@/components/admin-shell";
import { getMessagingOversight, getMessagingRoleSettings, updateMessagingRoleSetting, type MessageConversation, type MessagingRoleSetting } from "@/services/api";

function token() { return window.localStorage.getItem("anhh-staff-access-token") ?? ""; }

export function MessagingAdminPage() {
  const [roles, setRoles] = useState<MessagingRoleSetting[]>([]);
  const [conversations, setConversations] = useState<MessageConversation[]>([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState("");
  useEffect(() => { const accessToken = token(); Promise.all([getMessagingRoleSettings(accessToken), getMessagingOversight(accessToken)]).then(([roleRows, conversationRows]) => { setRoles(roleRows); setConversations(conversationRows); }).catch(reason => setError(reason instanceof Error ? reason.message : "Messaging settings could not be loaded.")).finally(() => setLoading(false)); }, []);
  async function toggle(row: MessagingRoleSetting) { try { const saved = await updateMessagingRoleSetting(row.role, !row.isEnabled, token()); setRoles(current => current.map(item => item.role === row.role ? saved : item)); toast.success(`${row.role} messaging ${saved.isEnabled ? "enabled" : "disabled"}.`); } catch (reason) { toast.error(reason instanceof Error ? reason.message : "Messaging setting could not be saved."); } }
  return <AdminShell superAdmin><div className="mx-auto max-w-6xl"><p className="text-xs font-black uppercase tracking-[0.2em] text-[#003893]">Superadmin control</p><h1 className="mt-2 text-3xl font-black text-slate-950">Messaging oversight</h1><p className="mt-2 text-sm text-slate-500">Control which roles can use messaging and review conversations when support or moderation requires it. Every oversight view is logged.</p>{error && <div className="mt-5 rounded-xl bg-rose-50 px-4 py-3 text-sm font-semibold text-rose-700">{error}</div>}{loading ? <div className="mt-6 rounded-2xl border bg-white p-6 text-sm text-slate-500">Loading messaging controls…</div> : <div className="mt-6 grid gap-6 lg:grid-cols-[330px_1fr]"><section className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><h2 className="flex items-center gap-2 font-black text-slate-950"><ShieldOff size={18} className="text-[#003893]" />Role controls</h2><p className="mt-1 text-xs text-slate-500">Disabled roles cannot send or receive new conversations.</p><div className="mt-4 space-y-2">{roles.map(row => <div key={row.role} className="flex items-center justify-between rounded-xl border border-slate-100 px-3 py-3"><span className="text-sm font-bold text-slate-800">{row.role}</span><button onClick={() => void toggle(row)} className={`rounded-full px-3 py-1 text-xs font-black ${row.isEnabled ? "bg-emerald-100 text-emerald-700" : "bg-slate-200 text-slate-500"}`}>{row.isEnabled ? "Enabled" : "Disabled"}</button></div>)}</div></section><section className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><h2 className="flex items-center gap-2 font-black text-slate-950"><Eye size={18} className="text-[#003893]" />Recent conversations</h2><p className="mt-1 text-xs text-slate-500">Read-only oversight list. Use the normal Messages inbox to reply according to your role.</p><div className="mt-4 space-y-2">{conversations.map(row => <div key={row.id} className="rounded-xl border border-slate-100 p-3"><div className="flex items-center justify-between gap-3"><span className="font-bold text-slate-900">{row.otherParticipantName}</span><span className="text-[10px] font-black uppercase text-slate-400">{row.otherParticipantRole}</span></div><p className="mt-1 truncate text-sm text-slate-500">{row.preview || "No messages yet"}</p></div>)}{conversations.length === 0 && <div className="rounded-xl bg-slate-50 p-8 text-center text-sm text-slate-500">No conversations found.</div>}</div></section></div>}</div></AdminShell>;
}
