"use client";

import Link from "next/link";
import { CheckCircle2, Clock3, PackageCheck, RefreshCw, Truck, XCircle } from "lucide-react";
import { useEffect, useState } from "react";
import { Card, CardContent } from "@/components/ui/card";
import { StaffShell, staffToken } from "@/components/staff-shell";
import { ApiError, getStaffDashboard, getStaffOrders, type DashboardStats, type Paged, type StaffOrderListItem } from "@/services/api";

export default function DeliveryDashboard() { const [stats, setStats] = useState<DashboardStats | null>(null); const [orders, setOrders] = useState<Paged<StaffOrderListItem> | null>(null); const [error, setError] = useState(""); const load = () => Promise.all([getStaffDashboard(staffToken(), "delivery"), getStaffOrders(staffToken(), "delivery", { today: true })]).then(([dashboard, list]) => { setStats(dashboard); setOrders(list); }).catch((e) => setError(e instanceof ApiError ? e.message : "Delivery dashboard could not be loaded.")); useEffect(() => { load(); }, []); return <StaffShell panel="delivery" title="Delivery dashboard" action={<button onClick={load} className="soft-btn"><RefreshCw size={15} /> Refresh</button>}>{error && <p className="mt-5 rounded-2xl bg-rose-50 p-4 text-sm font-semibold text-rose-700">{error}</p>}<div className="mt-7 grid gap-4 sm:grid-cols-2 xl:grid-cols-3">{[["Assigned today", "ASSIGNED_TODAY", Truck, "bg-teal-50 text-teal-700"], ["Pending pickup", "PENDING_PICKUP", PackageCheck, "bg-amber-50 text-amber-700"], ["Out for delivery", "OUT_FOR_DELIVERY", Clock3, "bg-blue-50 text-blue-700"], ["Delivered today", "DELIVERED_TODAY", CheckCircle2, "bg-emerald-50 text-emerald-700"], ["Failed deliveries", "FAILED_DELIVERIES", XCircle, "bg-rose-50 text-rose-700"], ["Total deliveries", "TOTAL_DELIVERIES", Truck, "bg-slate-100 text-slate-700"]].map(([label, key, Icon, tone]) => <Card key={key as string}><CardContent className="p-5"><span className={`flex h-10 w-10 items-center justify-center rounded-xl ${tone as string}`}><Icon size={19} /></span><p className="mt-5 text-xs font-bold text-slate-500">{label as string}</p><p className="mt-1 text-3xl font-extrabold">{stats ? stats.inventory[key as string] ?? 0 : "—"}</p></CardContent></Card>)}</div><section className="mt-7 rounded-2xl border border-slate-200 bg-white p-5"><div className="flex items-center justify-between"><div><p className="text-xs font-extrabold uppercase tracking-[0.15em] text-teal-700">Today</p><h2 className="mt-2 text-xl font-extrabold">Assigned deliveries</h2></div><Link href="/delivery/orders" className="text-xs font-extrabold text-teal-700">View all →</Link></div><div className="mt-5 grid gap-3">{orders?.items.slice(0, 5).map((order) => <Link key={order.id} href={`/delivery/orders/${order.id}`} className="flex flex-wrap items-center justify-between gap-3 rounded-xl border border-slate-100 p-4 hover:border-teal-200"><div><p className="font-extrabold">{order.orderNumber}</p><p className="mt-1 text-xs text-slate-500">{order.customerName} · {order.customerPhone}</p></div><div className="text-right"><p className="text-sm font-extrabold">Rs. {order.total.toLocaleString("en-IN")}</p><p className="mt-1 text-[11px] font-bold text-teal-700">{order.deliveryStatus ?? order.status}</p></div></Link>)}{orders?.items.length === 0 && <p className="py-12 text-center text-sm text-slate-500">No deliveries assigned today.</p>}</div></section></StaffShell>; }
