"use client";

import { useState, type FormEvent } from "react";
import { CheckCircle2, CircleAlert, Download, FileArchive, FileDown, FileSpreadsheet, Loader2, Upload } from "lucide-react";
import { toast } from "sonner";
import { AdminShell } from "@/components/admin-shell";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Checkbox } from "@/components/ui/checkbox";
import { commitAdminProductImport, commitCatalogWorkbook, downloadProductImportTemplate, previewAdminProductImport, previewCatalogWorkbook, type CatalogWorkbookImportResult, type CatalogWorkbookPreview, type ProductImportPreview, type ProductImportResult } from "@/services/api";

const getToken = () => typeof window === "undefined" ? "" : window.localStorage.getItem("anhh-staff-access-token") ?? "";

export function AdminProductImport({ superAdmin = true }: { superAdmin?: boolean }) {
  const [csv, setCsv] = useState<File>();
  const [images, setImages] = useState<File[]>([]);
  const [imagesZip, setImagesZip] = useState<File>();
  const [preview, setPreview] = useState<ProductImportPreview>();
  const [result, setResult] = useState<ProductImportResult>();
  const [busy, setBusy] = useState<"preview" | "commit" | "template" | "">("");
  const [replaceExisting, setReplaceExisting] = useState(false);
  const [workbook, setWorkbook] = useState<File>();
  const [workbookPreview, setWorkbookPreview] = useState<CatalogWorkbookPreview>();
  const [workbookResult, setWorkbookResult] = useState<CatalogWorkbookImportResult>();
  const [workbookBusy, setWorkbookBusy] = useState<"preview" | "commit" | "">("");

  async function downloadTemplate() { setBusy("template"); try { await downloadProductImportTemplate(getToken(), superAdmin); toast.success("CSV template downloaded."); } catch (error) { toast.error(error instanceof Error ? error.message : "The template could not be downloaded."); } finally { setBusy(""); } }
  async function previewUpload(event: FormEvent) {
    event.preventDefault(); if (!csv) { toast.error("Choose the CSV file first."); return; } if (!images.length && !imagesZip) { toast.error("Upload product images as multiple files or a ZIP."); return; }
    setBusy("preview"); setResult(undefined); try { setPreview(await previewAdminProductImport(csv, images, imagesZip, getToken(), superAdmin)); toast.success("CSV parsed. Review the validation results before saving."); } catch (error) { toast.error(error instanceof Error ? error.message : "The CSV could not be previewed."); } finally { setBusy(""); }
  }
  async function commitUpload() {
    if (!csv || !preview || preview.validRows === 0) return; setBusy("commit");
    try { const saved = await commitAdminProductImport(csv, images, imagesZip, replaceExisting, getToken(), superAdmin); setResult(saved); toast.success(`${saved.added} products added and ${saved.updated} products updated.`); } catch (error) { toast.error(error instanceof Error ? error.message : "The product import could not be saved."); } finally { setBusy(""); }
  }
  function downloadLog() { if (!result) return; const csvLog = ["metric,count", `added,${result.added}`, `updated,${result.updated}`, `failed,${result.failed}`, "", "errors", ...result.errors.map(error => `"${error.replaceAll('"', '""')}"`)].join("\n"); const url = URL.createObjectURL(new Blob([csvLog], { type: "text/csv;charset=utf-8" })); const anchor = document.createElement("a"); anchor.href = url; anchor.download = "product-import-log.csv"; anchor.click(); URL.revokeObjectURL(url); }
  async function previewWorkbookUpload(event: FormEvent) { event.preventDefault(); if (!workbook) { toast.error("Choose the .xlsx workbook first."); return; } setWorkbookBusy("preview"); setWorkbookResult(undefined); try { setWorkbookPreview(await previewCatalogWorkbook(workbook, getToken(), superAdmin)); toast.success("Workbook inspected. Review the detected header, duplicates, and missing-image status."); } catch (error) { toast.error(error instanceof Error ? error.message : "The workbook could not be previewed."); } finally { setWorkbookBusy(""); } }
  async function commitWorkbookUpload() { if (!workbook || !workbookPreview || workbookPreview.validRows === 0) return; setWorkbookBusy("commit"); try { const saved = await commitCatalogWorkbook(workbook, getToken(), superAdmin); setWorkbookResult(saved); toast.success(`${saved.added} products imported and ${saved.skippedDuplicates} duplicate rows skipped.`); } catch (error) { toast.error(error instanceof Error ? error.message : "The workbook could not be imported."); } finally { setWorkbookBusy(""); } }
  return <AdminShell superAdmin={superAdmin}>
    <div className="mb-7"><p className="text-xs font-extrabold uppercase tracking-[0.18em] text-[#DC143C]">Catalog tools</p><h1 className="mt-2 text-3xl font-extrabold tracking-tight">Bulk product upload</h1><p className="mt-2 text-sm text-slate-500">Import the workbook master catalog or upload a structured CSV. Every import is previewed before it changes the database.</p></div>
    <Card className="mb-6"><CardHeader><CardTitle className="flex items-center gap-2"><FileSpreadsheet size={18} className="text-[#003893]" />Import ALL PRODUCRS.xlsx</CardTitle><p className="mt-2 text-sm text-slate-500">The importer detects the real header row, keeps company code/name/product name, removes blank and duplicate rows, uses actual order history when available, and leaves an approved placeholder where no official image is verified.</p></CardHeader><CardContent><form onSubmit={previewWorkbookUpload} className="grid gap-4"><label className="grid gap-2 text-sm font-bold text-slate-700">Workbook (.xlsx)<input type="file" accept=".xlsx,application/vnd.openxmlformats-officedocument.spreadsheetml.sheet" onChange={event => { setWorkbook(event.target.files?.[0]); setWorkbookPreview(undefined); setWorkbookResult(undefined); }} className="block w-full rounded-lg border border-slate-200 bg-white p-2 text-sm font-normal" /></label><div className="rounded-xl border border-amber-100 bg-amber-50 p-4 text-sm leading-6 text-amber-900"><p className="font-bold">Image and demand handling</p><p>Images are not guessed. Imported rows start with the clean placeholder and “Missing / not verified”. Demand is labeled as sales history, a documented research proxy, or no evidence.</p></div><Button type="submit" disabled={workbookBusy !== ""}>{workbookBusy === "preview" ? <Loader2 className="animate-spin" /> : <Upload />}{workbookBusy === "preview" ? "Inspecting workbook…" : "Inspect and preview workbook"}</Button></form></CardContent></Card>
    {workbookPreview && <Card className="mb-6"><CardHeader><CardTitle>Workbook preview</CardTitle><p className="text-sm text-slate-500">{workbookPreview.totalRows} rows after the detected header · {workbookPreview.validRows} valid · {workbookPreview.duplicateRows} duplicates · {workbookPreview.invalidRows} invalid · {workbookPreview.blankRows} blank</p></CardHeader><CardContent><div className="overflow-x-auto rounded-xl border"><table className="w-full min-w-[1120px] text-sm"><thead><tr className="border-b bg-slate-50 text-left text-xs uppercase tracking-wide text-slate-500"><th className="px-3 py-3">Row</th><th className="px-3 py-3">Company code</th><th className="px-3 py-3">Company</th><th className="px-3 py-3">Product</th><th className="px-3 py-3">Image</th><th className="px-3 py-3">Demand</th><th className="px-3 py-3">Validation</th></tr></thead><tbody>{workbookPreview.rows.slice(0, 250).map(row => <tr key={row.rowNumber} className="border-b align-top last:border-0"><td className="px-3 py-3 font-bold">{row.rowNumber}</td><td className="px-3 py-3">{row.companyCode || "—"}</td><td className="px-3 py-3">{row.companyName || "—"}</td><td className="px-3 py-3 font-semibold">{row.productName || "—"}</td><td className="px-3 py-3"><Badge variant="secondary">{row.imageStatus}</Badge></td><td className="px-3 py-3"><span className="font-bold">{row.demandScore}</span><span className="block text-xs text-slate-500">{row.demandBasis.replaceAll("_", " ")}</span></td><td className="px-3 py-3">{row.isValid && !row.isDuplicate ? <span className="inline-flex items-center gap-1 font-bold text-emerald-700"><CheckCircle2 size={15} />Valid</span> : <span className="inline-flex items-start gap-1 font-semibold text-rose-700"><CircleAlert className="mt-0.5 shrink-0" size={15} /><span>{row.errors.join("; ")}</span></span>}</td></tr>)}</tbody></table></div>{workbookPreview.rows.length > 250 && <p className="mt-3 text-xs text-slate-500">Showing the first 250 rows here. The commit uses every valid unique row.</p>}<div className="mt-5 flex flex-wrap items-center justify-between gap-3"><p className="text-xs text-slate-500">No product changes are made until you confirm.</p><Button type="button" onClick={() => void commitWorkbookUpload()} disabled={workbookBusy !== "" || workbookPreview.validRows === 0}>{workbookBusy === "commit" ? <Loader2 className="animate-spin" /> : <CheckCircle2 />}{workbookBusy === "commit" ? "Importing catalog…" : `Import ${workbookPreview.validRows} valid rows`}</Button></div></CardContent></Card>}
    {workbookResult && <Card className="mb-6"><CardHeader><CardTitle>Workbook import summary</CardTitle></CardHeader><CardContent><div className="grid gap-3 text-sm sm:grid-cols-3 lg:grid-cols-6"><div className="rounded-xl bg-emerald-50 p-4"><p className="text-xs font-bold uppercase text-emerald-700">Added</p><p className="mt-1 text-2xl font-black text-emerald-800">{workbookResult.added}</p></div><div className="rounded-xl bg-blue-50 p-4"><p className="text-xs font-bold uppercase text-blue-700">Updated</p><p className="mt-1 text-2xl font-black text-blue-800">{workbookResult.updated}</p></div><div className="rounded-xl bg-slate-50 p-4"><p className="text-xs font-bold uppercase text-slate-700">Duplicates skipped</p><p className="mt-1 text-2xl font-black text-slate-800">{workbookResult.skippedDuplicates}</p></div><div className="rounded-xl bg-amber-50 p-4"><p className="text-xs font-bold uppercase text-amber-700">Missing images</p><p className="mt-1 text-2xl font-black text-amber-800">{workbookResult.missingImageRows}</p></div><div className="rounded-xl bg-violet-50 p-4"><p className="text-xs font-bold uppercase text-violet-700">Sales history</p><p className="mt-1 text-2xl font-black text-violet-800">{workbookResult.salesHistoryRows}</p></div><div className="rounded-xl bg-cyan-50 p-4"><p className="text-xs font-bold uppercase text-cyan-700">Research proxy</p><p className="mt-1 text-2xl font-black text-cyan-800">{workbookResult.researchBasedRows}</p></div></div>{workbookResult.errors.length > 0 && <div className="mt-4 rounded-xl bg-rose-50 p-4 text-sm text-rose-800"><p className="font-bold">Rows not imported</p><ul className="mt-2 max-h-48 list-disc space-y-1 overflow-y-auto pl-5">{workbookResult.errors.map(error => <li key={error}>{error}</li>)}</ul></div>}</CardContent></Card>}
    <Card><CardHeader className="flex-row items-start justify-between gap-4"><div><CardTitle className="flex items-center gap-2"><FileSpreadsheet size={18} className="text-[#003893]" />CSV upload</CardTitle><p className="mt-2 text-sm text-slate-500">Use the exact column names from the downloadable template.</p></div><Button type="button" variant="outline" onClick={() => void downloadTemplate()} disabled={busy !== ""}><FileDown />{busy === "template" ? "Preparing…" : "Download sample template"}</Button></CardHeader><CardContent><form onSubmit={previewUpload} className="grid gap-6"><label className="grid gap-2 text-sm font-bold text-slate-700">CSV file<input type="file" accept=".csv,text/csv" onChange={event => { setCsv(event.target.files?.[0]); setPreview(undefined); setResult(undefined); }} className="block w-full rounded-lg border border-slate-200 bg-white p-2 text-sm font-normal" /></label><label className="grid gap-2 text-sm font-bold text-slate-700">Images as separate files <span className="font-normal text-slate-500">(select multiple)</span><input type="file" accept="image/jpeg,image/png,image/webp,image/gif,image/bmp,image/avif" multiple onChange={event => setImages(Array.from(event.target.files ?? []))} className="block w-full rounded-lg border border-slate-200 bg-white p-2 text-sm font-normal" /></label><label className="grid gap-2 text-sm font-bold text-slate-700"><span className="flex items-center gap-2"><FileArchive size={16} />Or upload one image ZIP</span><input type="file" accept=".zip,application/zip" onChange={event => setImagesZip(event.target.files?.[0])} className="block w-full rounded-lg border border-slate-200 bg-white p-2 text-sm font-normal" /></label><div className="rounded-xl border border-blue-100 bg-blue-50 p-4 text-sm leading-6 text-blue-900"><p className="font-bold">Required columns</p><p>product_name, category, unit, sale_price, and branch_name. Each row must list at least one image_filename column; names are matched case-insensitively to the uploaded files.</p></div><label className="flex items-start gap-3 text-sm text-slate-700"><Checkbox checked={replaceExisting} onChange={event => setReplaceExisting(event.target.checked)} /><span><span className="font-bold">Deactivate products not included in this upload</span><span className="block text-xs text-slate-500">Safe replacement option. Existing order history is preserved.</span></span></label><Button type="submit" disabled={busy !== ""}>{busy === "preview" ? <Loader2 className="animate-spin" /> : <Upload />}{busy === "preview" ? "Parsing CSV…" : "Upload and preview"}</Button></form></CardContent></Card>
    {preview && <Card className="mt-6"><CardHeader><CardTitle>Review before saving</CardTitle><p className="text-sm text-slate-500">{preview.validRows} valid rows · {preview.errorRows} rows with errors. Only valid rows will be committed.</p></CardHeader><CardContent><div className="overflow-x-auto rounded-xl border"><table className="w-full min-w-[1100px] text-sm"><thead><tr className="border-b bg-slate-50 text-left text-xs uppercase tracking-wide text-slate-500"><th className="px-3 py-3">Row</th><th className="px-3 py-3">Product</th><th className="px-3 py-3">Category</th><th className="px-3 py-3">Branch</th><th className="px-3 py-3">Sale price</th><th className="px-3 py-3">Images</th><th className="px-3 py-3">Action</th><th className="px-3 py-3">Validation</th></tr></thead><tbody>{preview.rows.map(row => <tr key={row.rowNumber} className="border-b align-top last:border-0"><td className="px-3 py-3 font-bold">{row.rowNumber}</td><td className="px-3 py-3 font-semibold">{row.productName || "—"}{row.barcode && <span className="mt-1 block text-xs text-slate-400">{row.barcode}</span>}</td><td className="px-3 py-3">{row.category || "—"}</td><td className="px-3 py-3">{row.branchName || "—"}</td><td className="px-3 py-3">{row.salePrice == null ? "—" : `NPR ${row.salePrice.toLocaleString("en-NP")}`}</td><td className="max-w-[220px] px-3 py-3 text-xs text-slate-500">{row.imageFilenames.join(", ") || "—"}</td><td className="px-3 py-3">{row.willUpdate ? <Badge variant="secondary">Update</Badge> : <Badge>New</Badge>}</td><td className="px-3 py-3">{row.isValid ? <span className="inline-flex items-center gap-1 font-bold text-emerald-700"><CheckCircle2 size={15} />Valid</span> : <span className="inline-flex items-start gap-1 font-semibold text-rose-700"><CircleAlert className="mt-0.5 shrink-0" size={15} /><span>{row.errors.join("; ")}</span></span>}</td></tr>)}</tbody></table></div><div className="mt-5 flex flex-wrap items-center justify-between gap-3"><p className="text-xs text-slate-500">Confirming refreshes the shared product, inventory, search, cart, and hero data through the database-backed APIs.</p><Button type="button" onClick={() => void commitUpload()} disabled={busy !== "" || preview.validRows === 0}>{busy === "commit" ? <Loader2 className="animate-spin" /> : <CheckCircle2 />}{busy === "commit" ? "Saving…" : `Confirm ${preview.validRows} valid rows`}</Button></div></CardContent></Card>}
    {result && <Card className="mt-6"><CardHeader className="flex-row items-center justify-between"><CardTitle>Upload summary</CardTitle><Button type="button" variant="outline" size="sm" onClick={downloadLog}><Download />Download log</Button></CardHeader><CardContent><div className="grid gap-3 text-sm sm:grid-cols-3"><div className="rounded-xl bg-emerald-50 p-4"><p className="text-xs font-bold uppercase text-emerald-700">Added</p><p className="mt-1 text-2xl font-black text-emerald-800">{result.added}</p></div><div className="rounded-xl bg-blue-50 p-4"><p className="text-xs font-bold uppercase text-blue-700">Updated</p><p className="mt-1 text-2xl font-black text-blue-800">{result.updated}</p></div><div className="rounded-xl bg-rose-50 p-4"><p className="text-xs font-bold uppercase text-rose-700">Failed</p><p className="mt-1 text-2xl font-black text-rose-800">{result.failed}</p></div></div>{result.errors.length > 0 && <div className="mt-4 rounded-xl bg-rose-50 p-4 text-sm text-rose-800"><p className="font-bold">Failed rows</p><ul className="mt-2 list-disc space-y-1 pl-5">{result.errors.map(error => <li key={error}>{error}</li>)}</ul></div>}</CardContent></Card>}
  </AdminShell>;
}
