"use client";

import { useEffect, useState } from "react";
import { Building2, Download, FileText, Loader2, Printer, RefreshCw, Search, Users } from "lucide-react";
import { AdminShell } from "@/components/admin-shell";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Select } from "@/components/ui/select";
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table";
import { formatNPR } from "@/lib/catalog";
import { ApiError, getAdminCustomers, getBranchOperations, getCustomerStatement, type AdminCustomer, type BranchOperations, type CustomerStatement } from "@/services/api";

const today = () => { const now = new Date(); return new Date(now.getTime() - now.getTimezoneOffset() * 60_000).toISOString().slice(0, 10); };
const initialWeek = () => { const end = new Date(); const start = new Date(end); start.setDate(start.getDate() - 6); const toInput = (date: Date) => new Date(date.getTime() - date.getTimezoneOffset() * 60_000).toISOString().slice(0, 10); return { from: toInput(start), to: toInput(end) }; };
const csvCell = (value: unknown) => `"${String(value ?? "").replaceAll('"', '""')}"`;
function saveCsv(name: string, rows: unknown[][]) { const content = rows.map(row => row.map(csvCell).join(",")).join("\r\n"); const url = URL.createObjectURL(new Blob(["\uFEFF" + content], { type: "text/csv;charset=utf-8" })); const anchor = document.createElement("a"); anchor.href = url; anchor.download = name; anchor.click(); URL.revokeObjectURL(url); }

export function BranchOperationsPage({ superAdmin = false }: { superAdmin?: boolean }) {
  const [branches, setBranches] = useState<BranchOperations[]>([]);
  const [rows, setRows] = useState<BranchOperations[]>([]);
  const [branchId, setBranchId] = useState("");
  const [from, setFrom] = useState(today());
  const [to, setTo] = useState(today());
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState("");
  const [refresh, setRefresh] = useState(0);
  useEffect(() => { const token = localStorage.getItem("anhh-staff-access-token") ?? ""; if (!token) { setError("Sign in to view branch operations."); setLoading(false); return; } if (!from || !to) return; setLoading(true); setError(""); getBranchOperations(token, { from, to, branchId: branchId || undefined }, superAdmin).then(result => { setRows(result); if (!branchId) setBranches(result); }).catch(e => setError(e instanceof ApiError ? e.message : "Branch activity could not be loaded.")).finally(() => setLoading(false)); }, [superAdmin, from, to, branchId, refresh]);
  const exportCsv = () => saveCsv(`branch-operations-${from}-to-${to}.csv`, [["Branch", "Orders", "Customers", "Pharmacy orders", "Products", "Active riders", "Assigned riders", "Pending payments", "Paid payments", "Paid amount (NPR)", "Delivered", "Order value (NPR)"], ...rows.map(row => [row.branchName, row.orderCount, row.customerCount, row.pharmacyOrderCount, row.productCount, row.riderCount, row.assignedRiderCount, row.pendingPaymentCount, row.paidPaymentCount, row.paidPaymentAmount, row.deliveredCount, row.orderValue])]);
  return <AdminShell superAdmin={superAdmin}><main className="mx-auto grid w-full max-w-[1500px] gap-6 px-4 py-6 sm:px-6 lg:px-8"><header className="flex flex-wrap items-end justify-between gap-4"><div><p className="text-xs font-extrabold uppercase tracking-[0.16em] text-teal-700">Operations overview</p><h1 className="mt-2 text-3xl font-extrabold tracking-tight text-slate-950">Branch activity</h1><p className="mt-2 max-w-2xl text-sm text-slate-600">Live order, customer, product, payment, rider, and delivery totals from the selected date range.</p></div><div className="flex flex-wrap gap-2"><Button variant="outline" onClick={() => setRefresh(value => value + 1)}><RefreshCw size={15} />Refresh</Button><Button variant="outline" onClick={exportCsv} disabled={!rows.length}><Download size={15} />Export CSV</Button></div></header>
    <Card><CardContent className="grid gap-3 p-4 sm:grid-cols-3"><label className="grid gap-1.5 text-xs font-bold text-slate-600">From<Input type="date" value={from} max={to} onChange={event => setFrom(event.target.value)} /></label><label className="grid gap-1.5 text-xs font-bold text-slate-600">To<Input type="date" value={to} min={from} max={today()} onChange={event => setTo(event.target.value)} /></label><label className="grid gap-1.5 text-xs font-bold text-slate-600">Branch<Select value={branchId} onChange={event => setBranchId(event.target.value)}><option value="">All branches</option>{branches.map(branch => <option key={branch.branchId} value={branch.branchId}>{branch.branchName}</option>)}</Select></label></CardContent></Card>
    {error && <p role="alert" className="rounded-xl border border-rose-200 bg-rose-50 p-4 text-sm font-semibold text-rose-800">{error}</p>}
    {loading ? <div className="flex min-h-48 items-center justify-center text-sm text-slate-500"><Loader2 size={17} className="mr-2 animate-spin" />Loading branch activity…</div> : <>
      <div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4">{[["Orders", rows.reduce((sum, row) => sum + row.orderCount, 0)], ["Customers", rows.reduce((sum, row) => sum + row.customerCount, 0)], ["Pending payments", rows.reduce((sum, row) => sum + row.pendingPaymentCount, 0)], ["Delivered", rows.reduce((sum, row) => sum + row.deliveredCount, 0)]].map(([label, value]) => <Card key={String(label)}><CardContent className="p-4"><p className="text-xs font-bold uppercase tracking-wide text-slate-500">{label}</p><p className="mt-2 text-2xl font-extrabold text-slate-950">{value}</p></CardContent></Card>)}</div>
      <Card><CardHeader><CardTitle className="flex items-center gap-2"><Building2 size={18} className="text-teal-700" /> Branch breakdown</CardTitle></CardHeader><CardContent className="p-0"><div className="hidden overflow-x-auto md:block"><Table><TableHeader><TableRow><TableHead>Branch</TableHead><TableHead>Orders</TableHead><TableHead>Customers / pharmacies</TableHead><TableHead>Products</TableHead><TableHead>Riders</TableHead><TableHead>Payments</TableHead><TableHead>Delivered</TableHead><TableHead className="text-right">Order value</TableHead></TableRow></TableHeader><TableBody>{rows.map(row => <TableRow key={row.branchId}><TableCell className="font-bold">{row.branchName}</TableCell><TableCell>{row.orderCount}</TableCell><TableCell>{row.customerCount} <span className="text-xs text-slate-500">/ {row.pharmacyOrderCount}</span></TableCell><TableCell>{row.productCount}</TableCell><TableCell>{row.riderCount} active <span className="text-xs text-slate-500">/ {row.assignedRiderCount} assigned</span></TableCell><TableCell><span className="block">{row.paidPaymentCount} paid</span><span className="text-xs text-slate-500">{row.pendingPaymentCount} pending · {formatNPR(row.paidPaymentAmount)}</span></TableCell><TableCell>{row.deliveredCount}</TableCell><TableCell className="text-right font-extrabold">{formatNPR(row.orderValue)}</TableCell></TableRow>)}</TableBody></Table></div><div className="grid gap-3 p-4 md:hidden">{rows.map(row => <article key={row.branchId} className="rounded-xl border border-slate-200 p-4"><h2 className="font-extrabold">{row.branchName}</h2><div className="mt-3 grid grid-cols-2 gap-3 text-xs"><span>Orders <b className="block text-sm">{row.orderCount}</b></span><span>Customers <b className="block text-sm">{row.customerCount}</b></span><span>Pharmacy orders <b className="block text-sm">{row.pharmacyOrderCount}</b></span><span>Products <b className="block text-sm">{row.productCount}</b></span><span>Riders <b className="block text-sm">{row.riderCount} active · {row.assignedRiderCount} assigned</b></span><span>Payments <b className="block text-sm">{row.pendingPaymentCount} pending · {row.paidPaymentCount} paid</b></span><span>Paid amount <b className="block text-sm">{formatNPR(row.paidPaymentAmount)}</b></span><span>Delivered <b className="block text-sm">{row.deliveredCount}</b></span></div><p className="mt-3 border-t pt-3 text-right text-sm font-extrabold">Order value {formatNPR(row.orderValue)}</p></article>)}</div>{!rows.length && <div className="p-10 text-center text-sm text-slate-500">No branch activity is recorded for this period.</div>}</CardContent></Card>
    </>}</main></AdminShell>;
}

export function CustomerStatementsPage({ superAdmin = false }: { superAdmin?: boolean }) {
  const range = initialWeek();
  const [search, setSearch] = useState("");
  const [customers, setCustomers] = useState<AdminCustomer[]>([]);
  const [customerId, setCustomerId] = useState("");
  const [from, setFrom] = useState(range.from);
  const [to, setTo] = useState(range.to);
  const [statement, setStatement] = useState<CustomerStatement | null>(null);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState("");
  useEffect(() => { const timer = window.setTimeout(() => { const token = localStorage.getItem("anhh-staff-access-token") ?? ""; if (!token) return; getAdminCustomers(token, search, superAdmin).then(result => setCustomers(result.items)).catch(e => setError(e instanceof Error ? e.message : "Customer search failed.")); }, 250); return () => window.clearTimeout(timer); }, [search, superAdmin]);
  async function loadStatement() { if (!customerId) { setError("Choose a customer before loading their statement."); return; } const token = localStorage.getItem("anhh-staff-access-token") ?? ""; setLoading(true); setError(""); try { setStatement(await getCustomerStatement(token, customerId, { from, to }, superAdmin)); } catch (e) { setError(e instanceof ApiError ? e.message : "Statement could not be loaded."); setStatement(null); } finally { setLoading(false); } }
  const exportCsv = () => { if (!statement) return; saveCsv(`statement-${statement.customerId}-${from}-to-${to}.csv`, [["Customer", statement.customerName], ["Phone", statement.customerPhone], ["From", from], ["To", to], [], ["Order", "Date", "Status", "Payment method", "Payment status", "Billed (NPR)", "Paid (NPR)", "Balance (NPR)"], ...statement.orders.map(order => [order.orderNumber, new Date(order.createdAt).toLocaleDateString(), order.status, order.paymentMethod, order.paymentStatus, order.billedAmount, order.paidAmount, order.balance]), [], ["TOTAL", "", "", "", "", statement.billedAmount, statement.paidAmount, statement.balance]]); };
  return <AdminShell superAdmin={superAdmin}><main className="mx-auto grid w-full max-w-[1400px] gap-6 px-4 py-6 sm:px-6 lg:px-8"><header className="flex flex-wrap items-end justify-between gap-4"><div><p className="text-xs font-extrabold uppercase tracking-[0.16em] text-teal-700">Accounts and customer care</p><h1 className="mt-2 text-3xl font-extrabold tracking-tight">Customer statements</h1><p className="mt-2 text-sm text-slate-600">Review real orders and recorded payments for a customer or pharmacy, then print or export a statement.</p></div><div className="flex gap-2"><Button variant="outline" onClick={() => window.print()} disabled={!statement}><Printer size={15} />Print</Button><Button variant="outline" onClick={exportCsv} disabled={!statement}><Download size={15} />Export CSV</Button></div></header>
    <Card><CardContent className="grid gap-4 p-4 md:grid-cols-[1.5fr_1fr_1fr_auto] md:items-end"><div className="grid gap-1.5"><label htmlFor="statement-customer" className="text-xs font-bold text-slate-600">Search customer or pharmacy</label><div className="flex items-center rounded-xl border border-slate-200 px-3"><Search size={16} className="text-slate-400" /><input id="statement-customer" value={search} onChange={event => { setSearch(event.target.value); setCustomerId(""); }} placeholder="Name, phone, email" className="h-10 w-full bg-transparent px-2 text-sm outline-none" /></div><select value={customerId} onChange={event => setCustomerId(event.target.value)} className="mt-1 h-10 rounded-xl border border-slate-200 bg-white px-3 text-sm"><option value="">Select customer…</option>{customers.map(customer => <option key={customer.id} value={customer.id}>{customer.fullName} · {customer.phone}</option>)}</select></div><label className="grid gap-1.5 text-xs font-bold text-slate-600">From<Input type="date" value={from} max={to} onChange={event => setFrom(event.target.value)} /></label><label className="grid gap-1.5 text-xs font-bold text-slate-600">To<Input type="date" value={to} min={from} max={today()} onChange={event => setTo(event.target.value)} /></label><Button onClick={loadStatement} disabled={loading || !customerId}>{loading ? <Loader2 size={16} className="animate-spin" /> : <FileText size={16} />}Load statement</Button></CardContent></Card>
    {error && <p role="alert" className="rounded-xl border border-rose-200 bg-rose-50 p-4 text-sm font-semibold text-rose-800">{error}</p>}
    {statement && <section id="statement-print-area" className="grid gap-4"><Card><CardHeader><CardTitle>{statement.customerName}<span className="ml-2 text-sm font-medium text-slate-500">{statement.customerPhone}</span></CardTitle><p className="text-sm text-slate-500">{new Date(statement.from).toLocaleDateString()} — {new Date(statement.to).toLocaleDateString()} · {statement.orderCount} orders</p></CardHeader><CardContent className="grid grid-cols-1 gap-3 border-t pt-4 sm:grid-cols-3"><div><p className="text-xs font-bold uppercase text-slate-500">Billed</p><p className="mt-1 text-xl font-extrabold">{formatNPR(statement.billedAmount)}</p></div><div><p className="text-xs font-bold uppercase text-slate-500">Paid</p><p className="mt-1 text-xl font-extrabold text-emerald-700">{formatNPR(statement.paidAmount)}</p></div><div><p className="text-xs font-bold uppercase text-slate-500">Balance due</p><p className="mt-1 text-xl font-extrabold text-rose-700">{formatNPR(statement.balance)}</p></div></CardContent></Card><Card><CardHeader><CardTitle>Order ledger</CardTitle></CardHeader><CardContent className="p-0"><div className="overflow-x-auto"><Table><TableHeader><TableRow><TableHead>Order / date</TableHead><TableHead>Order status</TableHead><TableHead>Payment</TableHead><TableHead className="text-right">Billed</TableHead><TableHead className="text-right">Paid</TableHead><TableHead className="text-right">Balance</TableHead></TableRow></TableHeader><TableBody>{statement.orders.map(order => <TableRow key={order.orderId}><TableCell><b>{order.orderNumber}</b><span className="block text-xs text-slate-500">{new Date(order.createdAt).toLocaleString()}</span></TableCell><TableCell>{order.status.replaceAll("_", " ")}</TableCell><TableCell>{order.paymentMethod.replaceAll("_", " ")}<span className="block text-xs text-slate-500">{order.paymentStatus}</span></TableCell><TableCell className="text-right">{formatNPR(order.billedAmount)}</TableCell><TableCell className="text-right">{formatNPR(order.paidAmount)}</TableCell><TableCell className="text-right font-bold">{formatNPR(order.balance)}</TableCell></TableRow>)}</TableBody></Table></div>{!statement.orders.length && <p className="p-10 text-center text-sm text-slate-500">No orders in this statement period.</p>}</CardContent></Card></section>}
    {!statement && !loading && !error && <Card><CardContent className="grid justify-items-center gap-2 p-12 text-center"><Users className="text-slate-300" size={34} /><p className="font-bold">Choose a customer and date range.</p><p className="text-sm text-slate-500">The statement is calculated from saved orders and successful payment records.</p></CardContent></Card>}</main></AdminShell>;
}
