"use client";

/* eslint-disable react-hooks/exhaustive-deps */

import { Boxes, RefreshCw } from "lucide-react";
import { useEffect, useState } from "react";
import { StaffShell, staffToken } from "@/components/staff-shell";
import { ApiError, getInventory, type InventoryItem, type Paged } from "@/services/api";

export function InventoryScreen({ filter, title }: { filter?: string; title: string }) { const [data, setData] = useState<Paged<InventoryItem> | null>(null); const [error, setError] = useState(""); const load = () => getInventory(staffToken(), filter).then(setData).catch((e) => setError(e instanceof ApiError ? e.message : "Inventory could not be loaded.")); useEffect(() => { load(); }, [filter]); return <StaffShell panel="pharmacist" title={title} action={<button onClick={load} className="soft-btn"><RefreshCw size={15} /> Refresh</button>}><p className="-mt-3 text-sm text-slate-500">Live branch inventory with reserved quantities separated from available stock.</p>{error && <p className="mt-5 rounded-2xl bg-rose-50 p-4 text-sm font-semibold text-rose-700">{error}</p>}<div className="mt-6 overflow-hidden rounded-2xl border border-slate-200 bg-white"><div className="overflow-x-auto"><table className="w-full min-w-[900px] text-left text-sm"><thead className="border-b border-slate-100 bg-slate-50 text-xs font-extrabold uppercase tracking-wide text-slate-500"><tr><th className="px-5 py-4">Medicine</th><th className="px-5 py-4">SKU / batch</th><th className="px-5 py-4">Branch</th><th className="px-5 py-4">Stock</th><th className="px-5 py-4">Reserved</th><th className="px-5 py-4">Available</th><th className="px-5 py-4">Status</th></tr></thead><tbody className="divide-y divide-slate-100">{data?.items.map((item) => <tr key={item.id} className="hover:bg-slate-50"><td className="px-5 py-4"><p className="font-extrabold">{item.medicine}</p><p className="mt-1 text-xs text-slate-500">{item.genericName} · {item.brand}</p></td><td className="px-5 py-4 text-xs text-slate-500">{item.sku}<br />{item.batchNumber}</td><td className="px-5 py-4 text-xs text-slate-500">{item.branch}</td><td className="px-5 py-4 font-bold">{item.stockQuantity}</td><td className="px-5 py-4 text-amber-700">{item.reservedQuantity}</td><td className="px-5 py-4 font-extrabold text-teal-700">{item.availableQuantity}</td><td className="px-5 py-4"><span className={`rounded-full px-2.5 py-1 text-[10px] font-extrabold ${item.status === "OUT_OF_STOCK" ? "bg-rose-100 text-rose-800" : item.status === "LOW_STOCK" ? "bg-amber-100 text-amber-800" : "bg-emerald-100 text-emerald-800"}`}>{item.status.replaceAll("_", " ")}</span></td></tr>)}</tbody></table></div>{data?.items.length === 0 && <div className="px-6 py-20 text-center"><Boxes className="mx-auto text-slate-300" size={38} /><p className="mt-4 font-extrabold">No inventory rows match this view.</p><p className="mt-2 text-sm text-slate-500">Expiry fields will populate when batch inventory is introduced.</p></div>}</div></StaffShell>; }
