"use client";

/* eslint-disable react-hooks/exhaustive-deps */

import { Bell, CheckCheck, RefreshCw } from "lucide-react";
import { useEffect, useState } from "react";
import { StaffShell, staffToken } from "@/components/staff-shell";
import { ApiError, getStaffNotifications, markAllStaffNotificationsRead, markStaffNotificationRead, type StaffNotification } from "@/services/api";
import { formatNepalDateTime } from "@/lib/date-time";

export function StaffNotifications({ panel }: { panel: "pharmacist" | "delivery" }) { const [rows, setRows] = useState<StaffNotification[]>([]); const [error, setError] = useState(""); const load = () => getStaffNotifications(staffToken(), panel).then(setRows).catch((e) => setError(e instanceof ApiError ? e.message : "Notifications could not be loaded.")); useEffect(() => { load(); }, [panel]); async function read(id: string) { setError(""); try { await markStaffNotificationRead(id, staffToken(), panel); setRows((current) => current.map((item) => item.id === id ? { ...item, isRead: true } : item)); } catch (e) { setError(e instanceof ApiError ? e.message : "Notification could not be marked as read."); } } async function readAll() { setError(""); try { await markAllStaffNotificationsRead(staffToken(), panel); setRows((current) => current.map((item) => ({ ...item, isRead: true }))); } catch (e) { setError(e instanceof ApiError ? e.message : "Notifications could not be marked as read."); } } return <StaffShell panel={panel} title="Notifications" action={<div className="flex gap-2"><button onClick={() => void readAll()} className="soft-btn"><CheckCheck size={15} /> Mark all read</button><button onClick={load} className="soft-btn"><RefreshCw size={15} /></button></div>}>{error && <p className="mb-5 rounded-2xl bg-rose-50 p-4 text-sm font-semibold text-rose-700">{error}</p>}<div className="grid gap-3">{rows.map((item) => <button key={item.id} onClick={() => void read(item.id)} className={`rounded-2xl border p-5 text-left transition hover:border-teal-200 ${item.isRead ? "border-slate-200 bg-white" : "border-teal-200 bg-teal-50/60"}`}><div className="flex gap-4"><span className="flex h-10 w-10 shrink-0 items-center justify-center rounded-xl bg-white text-teal-700 shadow-sm"><Bell size={18} /></span><div className="min-w-0"><div className="flex flex-wrap items-center gap-2"><p className="font-extrabold">{item.title}</p>{!item.isRead && <span className="rounded-full bg-teal-600 px-2 py-0.5 text-[10px] font-bold text-white">Unread</span>}</div><p className="mt-1 text-sm leading-6 text-slate-600">{item.body}</p><p className="mt-2 text-xs text-slate-400">{formatNepalDateTime(item.createdAt)}</p></div></div></button>)}{!rows.length && <div className="rounded-2xl border border-slate-200 bg-white px-6 py-20 text-center"><Bell className="mx-auto text-slate-300" size={38} /><p className="mt-4 font-extrabold">No notifications yet.</p><p className="mt-2 text-sm text-slate-500">Operational alerts will appear here.</p></div>}</div></StaffShell>; }
