"use client";

import { History, RefreshCw } from "lucide-react";
import { useEffect, useState } from "react";
import { StaffShell, staffToken } from "@/components/staff-shell";
import { ApiError, getStaffActivity, type StaffActivity } from "@/services/api";
import { formatNepalDateTime } from "@/lib/date-time";

export default function ActivityPage() { const [rows, setRows] = useState<StaffActivity[]>([]); const [error, setError] = useState(""); const load = () => getStaffActivity(staffToken()).then(setRows).catch((e) => setError(e instanceof ApiError ? e.message : "Activity could not be loaded.")); useEffect(() => { load(); }, []); return <StaffShell panel="pharmacist" title="Activity history" action={<button onClick={load} className="soft-btn"><RefreshCw size={15} /> Refresh</button>}>{error && <p className="mb-5 rounded-2xl bg-rose-50 p-4 text-sm font-semibold text-rose-700">{error}</p>}<div className="overflow-hidden rounded-2xl border border-slate-200 bg-white"><div className="overflow-x-auto"><table className="w-full min-w-[760px] text-left text-sm"><thead className="border-b border-slate-100 bg-slate-50 text-xs font-extrabold uppercase tracking-wide text-slate-500"><tr><th className="px-5 py-4">Action</th><th className="px-5 py-4">Entity</th><th className="px-5 py-4">Change</th><th className="px-5 py-4">Time</th></tr></thead><tbody className="divide-y divide-slate-100">{rows.map((item) => <tr key={item.id}><td className="px-5 py-4"><p className="font-extrabold">{item.action.replaceAll("_", " ")}</p><p className="mt-1 text-xs text-slate-400">{item.actorRole ?? "System"}</p></td><td className="px-5 py-4 text-xs text-slate-500">{item.entityType}<br />{item.entityId}</td><td className="px-5 py-4 text-xs text-slate-600">{item.previousValue ?? "—"} → {item.newValue ?? "—"}</td><td className="px-5 py-4 text-xs text-slate-500">{formatNepalDateTime(item.createdAt)}</td></tr>)}</tbody></table></div>{!rows.length && <div className="px-6 py-20 text-center"><History className="mx-auto text-slate-300" size={38} /><p className="mt-4 font-extrabold">No activity has been recorded.</p></div>}</div></StaffShell>; }
