namespace backend.Contracts;

public sealed record DashboardStatsResponse(IReadOnlyDictionary<string, int> Prescriptions, IReadOnlyDictionary<string, int> Orders, IReadOnlyDictionary<string, int> Inventory);
public sealed record StaffPrescriptionListItem(Guid Id, string PrescriptionNumber, Guid CustomerId, string CustomerName, string CustomerPhone, DateTime SubmittedAt, int MedicineCount, decimal OcrConfidence, string Status, string ReviewStatus, string? AssignedPharmacist, string Priority, Guid? RelatedOrderId);
public sealed record StaffPrescriptionResponse(Guid Id, string PrescriptionNumber, string CustomerName, string CustomerPhone, string CustomerEmail, DateTime CreatedAt, DateTime? SubmittedAt, string OriginalFileName, string ContentType, string Status, string? OcrProvider, string? OcrStatus, string? OcrText, string? CustomerNote, IReadOnlyList<StaffPrescriptionItem> Items, IReadOnlyList<StatusHistoryItem> Timeline, IReadOnlyList<ReviewItem> Reviews);
public sealed record StaffPrescriptionItem(Guid Id, string DetectedName, string NormalizedName, string? Strength, string? DosageForm, int? Quantity, string? Frequency, string? Duration, string? Instructions, decimal OcrConfidence, StaffMatchItem? Match, string? Dosage = null, string? Timing = null);
public sealed record StaffMatchItem(Guid Id, Guid? ProductId, string? ProductName, string? GenericName, string? Brand, decimal? SellingPrice, decimal Confidence, string MatchType, string Availability, int StockQuantity, bool NeedsPharmacistReview, bool PrescriptionRequired);
public sealed record StatusHistoryItem(string Status, string? Note, string? Actor, string? ActorRole, DateTime CreatedAt);
public sealed record ReviewItem(string Status, string? Notes, string? Reviewer, DateTime? ReviewedAt, DateTime CreatedAt);
public sealed record ReviewMedicineRequest(Guid? ProductId, int? Quantity, string Availability, string? Note);
public sealed record PrescriptionDecisionRequest(string? Notes, IReadOnlyDictionary<Guid, ReviewMedicineRequest>? Items);
public sealed record PrescriptionClarificationRequest(string Message, Guid? ItemId);
public sealed record PrescriptionRejectionRequest(string Reason, string? Notes);
public sealed record StaffOrderListItem(Guid Id, string OrderNumber, string CustomerName, string CustomerPhone, DateTime CreatedAt, string Status, string PaymentStatus, string PaymentMethod, decimal Total, bool PrescriptionRequired, string? DeliveryStatus, string? DeliveryStaff, string? BranchName = null, string OrderMode = "SINGLE", bool PricesVisible = true);
public sealed record StaffOrderResponse(Guid Id, string OrderNumber, string CustomerName, string CustomerEmail, string CustomerPhone, DateTime CreatedAt, string Status, string PaymentStatus, string PaymentMethod, decimal Total, decimal DeliveryFee, string? DeliveryInstructions, StaffAddressItem? Address, IReadOnlyList<StaffOrderItem> Items, StaffPrescriptionSummary? Prescription, IReadOnlyList<StatusHistoryItem> Timeline, DeliverySummary? Delivery, Guid? BranchId = null, string? BranchName = null, Guid? PharmacistId = null, string? PharmacistName = null, Guid? DeliverySlotId = null, string? DeliverySlotLabel = null, string? CustomerNotes = null, string OrderMode = "SINGLE", IReadOnlyList<OrderDocumentRow>? Documents = null, bool PricesVisible = true);
public sealed record StaffOrderItem(Guid Id, string ProductName, int Quantity, decimal UnitPrice, string Sku, bool PrescriptionRequired);
public sealed record StaffAddressItem(string Label, string Province, string District, string Municipality, string Ward, string StreetTole, string? Landmark, string Phone, decimal? Latitude = null, decimal? Longitude = null);
public sealed record OrderDocumentRow(Guid Id, string Kind, string OriginalFileName, string ContentType, long Length, DateTime CreatedAt, string DownloadUrl);
public sealed record StaffPrescriptionSummary(Guid Id, string Status, string? Notes);
public sealed record DeliverySummary(Guid Id, Guid DeliveryStaffId, string DeliveryStaff, string Status, DateTime? AcceptedAt, DateTime? PickedUpAt, DateTime? OutForDeliveryAt, DateTime? DeliveredAt, DateTime? FailedAt, string? FailureReason, string? Notes, DeliveryCurrentLocation? CurrentLocation = null, DeliveryPickup? Pickup = null);
public sealed record DeliveryCurrentLocation(decimal Latitude, decimal Longitude, decimal Accuracy, DateTime UpdatedAt);
public sealed record DeliveryPickup(decimal Latitude, decimal Longitude, string Address);
public sealed record OrderStatusRequest(string Status, string? Note);
public sealed record InventoryListItem(Guid Id, Guid ProductId, string Medicine, string GenericName, string Brand, string Sku, string BatchNumber, int StockQuantity, int ReservedQuantity, int AvailableQuantity, decimal Mrp, decimal SellingPrice, DateTime? ExpiryDate, string Branch, string Status, int MinimumStock);
public sealed record StaffCustomerListItem(Guid Id, string FullName, string Email, string Phone, int Orders, int Prescriptions, DateTime? LastOrder, bool IsActive);
public sealed record StaffNotificationItem(Guid Id, string Type, string Title, string Body, bool IsRead, DateTime CreatedAt);
public sealed record StaffActivityItem(Guid Id, string Action, string EntityType, string EntityId, string? ActorRole, string? PreviousValue, string? NewValue, DateTime CreatedAt);
public sealed record StaffProfileResponse(Guid Id, string FullName, string Email, string Phone, string Role, Guid? BranchId, string? BranchName, string? LicenseReference, bool IsActive, string? EmployeeId = null, string? Address = null, DateTime? JoiningDate = null, string? ProfilePhotoUrl = null);
public sealed record UpdateStaffProfileRequest(string FullName, string Phone, string? LicenseReference, string? EmployeeId = null, string? Address = null, DateTime? JoiningDate = null);
public sealed record CustomerWishlistItem(Guid ProductId, string ProductCode);
public sealed record CustomerCartLine(Guid ProductId, string ProductCode, string ProductSlug, string ProductName, int Quantity, int AvailableQuantity, bool PrescriptionRequired, string? ImageUrl, decimal SellingPrice, bool PricesVisible = true);
public sealed record CustomerCartResponse(IReadOnlyList<CustomerCartLine> Items, IReadOnlyList<string> Warnings, int Count);
public sealed record MergeCustomerCartRequest(IReadOnlyList<MergeCustomerCartLine> Items);
public sealed record MergeCustomerCartLine(string ProductCode, int Quantity);
public sealed record CustomerCartItemRequest(string ProductCode, int Quantity);
public sealed record CustomerCartQuantityRequest(int Quantity);
public sealed record ChangePasswordRequest(string CurrentPassword, string NewPassword, string ConfirmPassword);
public sealed record DeliveryFailureRequest(string Reason, string? Notes);
public sealed record DeliveryNoteRequest(string? Notes, decimal? Latitude = null, decimal? Longitude = null);
public sealed record DeliveryLocationUpdateRequest(double? Latitude, double? Longitude, double? Accuracy);
public sealed record RiderAvailabilityUpdateRequest(bool IsAvailable);
public sealed record RiderAvailabilityResponse(bool IsAvailable, bool HasActiveDelivery, RiderAvailabilityLocation? Location);
public sealed record RiderAvailabilityLocation(decimal Latitude, decimal Longitude, decimal? Accuracy, DateTime UpdatedAt);
public sealed record NearbyRiderCandidate(Guid RiderId, string RiderName, double DistanceMeters, bool IsAvailable, DateTime LastUpdatedAt);
public sealed record CustomerLiveTrackingResponse(Guid OrderId, string OrderNumber, string? DeliveryStatus, string? RiderName, CustomerLiveLocation? Location, CustomerLiveDestination? Destination);
public sealed record CustomerLiveLocation(decimal Latitude, decimal Longitude, decimal? Accuracy, DateTime UpdatedAt);
public sealed record CustomerLiveDestination(decimal Latitude, decimal Longitude, string Address);
public sealed record LiveDeliveryMapRow(Guid OrderId, string OrderNumber, string RiderName, string DeliveryStatus, CustomerLiveLocation? Location, CustomerLiveDestination? Destination, string? DestinationAddress);
public sealed record PaymentInstructionsResponse(string OrderNumber, string PaymentMethod, string PaymentStatus, decimal AmountDue, string? Instructions, string? QrCodeUrl);
public sealed record PriceVisibilityResponse(bool PricesVisible);
public sealed record ManualOrderItemRequest(Guid ProductId, int Quantity);
public sealed record ManualRiderOrderRequest(Guid CustomerId, Guid AddressId, IReadOnlyList<ManualOrderItemRequest> Items, string? PaymentMethod, string? Notes, string? OrderMode);
public sealed record ManualOrderCustomer(Guid Id, string Name, string Phone, string Email, string AccountType, IReadOnlyList<ManualOrderAddress> Addresses);
public sealed record ManualOrderAddress(Guid Id, string Label, string Province, string District, string Municipality, string Ward, string StreetTole, string? Landmark, string Phone, decimal? Latitude, decimal? Longitude);
public sealed record BranchOperationsRow(Guid BranchId, string BranchName, int OrderCount, int CustomerCount, int PharmacyOrderCount, int PendingPaymentCount, int AssignedRiderCount, int DeliveredCount, decimal OrderValue, DateTime RangeStart, DateTime RangeEnd, int ProductCount = 0, int RiderCount = 0, int PaidPaymentCount = 0, decimal PaidPaymentAmount = 0);
public sealed record ManualOrderProduct(Guid Id, string Name, string Sku, string Unit, decimal SellingPrice, int AvailableQuantity, bool PrescriptionRequired, bool AllowBulk, bool AllowSingle, int MinimumQuantity);
public sealed record ManualRiderOrderSettings(string Mode, int MinimumBulkQuantity);
public sealed record CustomerStatementLine(Guid OrderId, string OrderNumber, DateTime CreatedAt, string Status, string PaymentStatus, string PaymentMethod, decimal BilledAmount, decimal PaidAmount, decimal Balance);
public sealed record CustomerStatementResponse(Guid CustomerId, string CustomerName, string CustomerPhone, DateTime From, DateTime To, int OrderCount, decimal BilledAmount, decimal PaidAmount, decimal Balance, IReadOnlyList<CustomerStatementLine> Orders);
public sealed record AssignDeliveryRequest(Guid DeliveryStaffId, string? Notes);
public sealed record CreateOrderItemRequest(string ProductCode, int Quantity);
public sealed record CreateOrderRequest(IReadOnlyList<CreateOrderItemRequest> Items, string FullName, string Phone, string Email, string Province, string District, string Municipality, string Ward, string StreetTole, string? Landmark, string? DeliveryInstructions, Guid? PrescriptionId, string? CouponCode = null, string? PaymentMethod = null, Guid? DeliverySlotId = null, Guid? BranchId = null, string? OrderMode = null, string? Locale = null, string? Notes = null, decimal? Latitude = null, decimal? Longitude = null);
public sealed record DeliveryQuoteRequest(string Province, string District, string Municipality, string Ward, decimal Subtotal, Guid? BranchId = null, IReadOnlyList<CreateOrderItemRequest>? Items = null);
public sealed record DeliveryQuoteResponse(string? ZoneName, decimal DeliveryFee, decimal FreeDeliveryThreshold, decimal MinimumOrder, bool SameDayDelivery);
public sealed record CouponValidationRequest(string Code, decimal Subtotal);
public sealed record CouponValidationResponse(string Code, string Type, decimal Value, decimal DiscountAmount, decimal Subtotal, decimal TotalAfterDiscount);
public sealed record CustomerOrderResponse(Guid Id, string OrderNumber, string Status, decimal Total, DateTime CreatedAt);
public sealed record PublicOrderTrackingEvent(string Status, DateTime CreatedAt);
public sealed record PublicOrderTrackingResponse(string TrackingId, string OrderNumber, string Status, string? DeliveryStatus, decimal Total, DateTime CreatedAt, string? BranchName, IReadOnlyList<PublicOrderTrackingEvent> Timeline, bool PricesVisible = true);
