"use client";

/* eslint-disable react-hooks/exhaustive-deps */

import { RefreshCw, Search, Users } from "lucide-react";
import { useEffect, useState } from "react";
import { StaffShell, staffToken } from "@/components/staff-shell";
import { ActiveStatusToggle } from "@/components/active-status-toggle";
import { ApiError, getStaffCustomers, type StaffCustomer } from "@/services/api";
import { formatPlatformDate } from "@/lib/date-time";

export default function PharmacistCustomers() { const [rows, setRows] = useState<StaffCustomer[]>([]); const [search, setSearch] = useState(""); const [error, setError] = useState(""); const load = () => getStaffCustomers(staffToken(), search || undefined).then(setRows).catch((e) => setError(e instanceof ApiError ? e.message : "Customers could not be loaded.")); useEffect(() => { load(); }, []); return <StaffShell panel="pharmacist" title="Customers" action={<button onClick={load} className="soft-btn"><RefreshCw size={15} /> Refresh</button>}><div className="flex gap-3 rounded-2xl border border-slate-200 bg-white p-4"><div className="flex flex-1 items-center gap-2 rounded-xl border border-slate-200 px-3"><Search size={16} className="text-slate-400" /><input value={search} onChange={(e) => setSearch(e.target.value)} onKeyDown={(e) => e.key === "Enter" && load()} className="w-full bg-transparent py-2.5 text-sm outline-none" placeholder="Search name, phone, or email" /></div><button onClick={load} className="primary-btn">Search</button></div>{error && <p className="mt-5 rounded-2xl bg-rose-50 p-4 text-sm font-semibold text-rose-700">{error}</p>}<div className="mt-6 overflow-hidden rounded-2xl border border-slate-200 bg-white"><div className="overflow-x-auto"><table className="w-full min-w-[760px] text-left text-sm"><thead className="border-b border-slate-100 bg-slate-50 text-xs font-extrabold uppercase tracking-wide text-slate-500"><tr><th className="px-5 py-4">Customer</th><th className="px-5 py-4">Contact</th><th className="px-5 py-4">Orders</th><th className="px-5 py-4">Prescriptions</th><th className="px-5 py-4">Last order</th><th className="px-5 py-4">Account</th></tr></thead><tbody className="divide-y divide-slate-100">{rows.map((customer) => <tr key={customer.id}><td className="px-5 py-4 font-extrabold">{customer.fullName}</td><td className="px-5 py-4 text-xs text-slate-500">{customer.phone}<br />{customer.email}</td><td className="px-5 py-4 font-bold">{customer.orders}</td><td className="px-5 py-4 font-bold">{customer.prescriptions}</td><td className="px-5 py-4 text-xs text-slate-500">{customer.lastOrder ? formatPlatformDate(customer.lastOrder) : "—"}</td><td className="px-5 py-4"><ActiveStatusToggle checked={customer.isActive} onChange={() => undefined} disabled label={"customer " + customer.fullName} /></td></tr>)}</tbody></table></div>{!rows.length && <div className="px-6 py-20 text-center"><Users className="mx-auto text-slate-300" size={38} /><p className="mt-4 font-extrabold">No customers found.</p></div>}</div></StaffShell>; }
