import {
  Activity,
  BarChart3,
  Bell,
  BookOpen,
  Boxes,
  CalendarDays,
  CheckSquare,
  ClipboardList,
  CreditCard,
  FileText,
  Headphones,
  Images,
  KeyRound,
  LayoutDashboard,
  MapPin,
  Menu,
  MessageSquare,
  Palette,
  Package,
  Receipt,
  Settings,
  Shield,
  Sparkles,
  Store,
  Tags,
  TimerReset,
  Truck,
  Users,
  Wallet,
  type LucideIcon,
} from "lucide-react";

const iconEntries: Array<[string, string, LucideIcon]> = [
  ["ACTIVITY", "Activity", Activity],
  ["BAR_CHART_3", "Reports", BarChart3],
  ["BELL", "Notifications", Bell],
  ["BOOK_OPEN", "Open book", BookOpen],
  ["BOXES", "Inventory", Boxes],
  ["CALENDAR_DAYS", "Calendar", CalendarDays],
  ["CHECK_SQUARE", "Checklist", CheckSquare],
  ["CLIPBOARD_LIST", "Clipboard", ClipboardList],
  ["CREDIT_CARD", "Payments", CreditCard],
  ["FILE_TEXT", "Documents", FileText],
  ["HEADPHONES", "Support", Headphones],
  ["IMAGES", "Images", Images],
  ["KEY_ROUND", "Access", KeyRound],
  ["LAYOUT_DASHBOARD", "Dashboard", LayoutDashboard],
  ["MAP_PIN", "Location", MapPin],
  ["MENU", "Menu", Menu],
  ["MESSAGE_SQUARE", "Messages", MessageSquare],
  ["PALETTE", "Design", Palette],
  ["PACKAGE", "Package", Package],
  ["RECEIPT", "Receipt", Receipt],
  ["SETTINGS", "Settings", Settings],
  ["SHIELD", "Security", Shield],
  ["SPARKLES", "Highlights", Sparkles],
  ["STORE", "Store", Store],
  ["TAGS", "Catalog", Tags],
  ["TIMER_RESET", "Timer", TimerReset],
  ["TRUCK", "Delivery", Truck],
  ["USERS", "People", Users],
  ["WALLET", "Wallet", Wallet],
];

export const SIDEBAR_ICONS: Array<{ name: string; label: string; Icon: LucideIcon }> = iconEntries.map(([name, label, Icon]) => ({ name, label, Icon }));

export function resolveSidebarIcon(name?: string): LucideIcon {
  return SIDEBAR_ICONS.find((item) => item.name === name?.toUpperCase())?.Icon ?? Menu;
}
